#!/bin/bash
# ══════════════════════════════════════════════════════
# FitTrack Build Script
# Used by Vercel and Netlify to generate config.js
# from environment variables set in their dashboards.
#
# Vercel:  Settings → Build & Output → Build Command → bash build.sh
# Netlify: netlify.toml [build] command = "bash build.sh"
# ══════════════════════════════════════════════════════

echo "🔨 FitTrack build started..."

# Generate config.js from environment variables
cat > config.js << CONFIGEOF
// Auto-generated by build.sh — DO NOT EDIT MANUALLY
var CONFIG = {
  firebase: {
    apiKey:            "${FIREBASE_API_KEY}",
    authDomain:        "${FIREBASE_AUTH_DOMAIN}",
    projectId:         "${FIREBASE_PROJECT_ID}",
    storageBucket:     "${FIREBASE_STORAGE_BUCKET}",
    messagingSenderId: "${FIREBASE_MESSAGING_SENDER_ID}",
    appId:             "${FIREBASE_APP_ID}"
  },
  supabase: {
    url:     "${SUPABASE_URL}",
    anonKey: "${SUPABASE_ANON_KEY}"
  },
  recaptchaSiteKey: "${RECAPTCHA_SITE_KEY}",
  siteUrl: "${SITE_URL}",
};
CONFIGEOF

# Update all HTML files to load config.js instead of config.local.js
find . -name "*.html" -not -path "./.git/*" -not -path "./node_modules/*" | while read file; do
  sed -i 's|config\.local\.js|config.js|g' "$file"
done

echo "✅ config.js generated"
echo "✅ HTML files updated to use config.js"
echo "✅ Build complete!"